/** Generated by `npm run audio:prepare`. Do not edit by hand. */
export const AMBIENT_AUDIO_URLS = [
  "/audio/ambient/ambient-01.webm",
  "/audio/ambient/ambient-02.webm",
  "/audio/ambient/ambient-03.webm",
  "/audio/ambient/ambient-04.webm",
  "/audio/ambient/ambient-05.webm",
  "/audio/ambient/ambient-06.webm",
  "/audio/ambient/ambient-07.webm",
] as const;

export const FOOTSTEP_AUDIO_URLS = [
  "/audio/steps/step-01.wav",
  "/audio/steps/step-02.wav",
  "/audio/steps/step-03.wav",
  "/audio/steps/step-04.wav",
  "/audio/steps/step-05.wav",
  "/audio/steps/step-06.wav",
  "/audio/steps/step-07.wav",
  "/audio/steps/step-08.wav",
  "/audio/steps/step-09.wav",
  "/audio/steps/step-10.wav",
  "/audio/steps/step-11.wav",
  "/audio/steps/step-12.wav",
] as const;
