/** Generated by `npm run audio:prepare`. Do not edit by hand. */
export const AMBIENT_AUDIO_URL = "/audio/ambient/ambient-01.wav";
export const BOT_RUNNING_AUDIO_URL = "/audio/bot-running/bot-running.webm";
export const TURNING_AUDIO_URL = "/audio/turning/turning-loop.wav";

export const FOOTSTEP_AUDIO_URLS = [
  "/audio/steps/step-01.wav",
  "/audio/steps/step-02.wav",
  "/audio/steps/step-03.wav",
  "/audio/steps/step-04.wav",
  "/audio/steps/step-05.wav",
  "/audio/steps/step-06.wav",
] as const;
