/** Generated by `npm run audio:prepare`. Do not edit by hand. */
export const BOT_RUNNING_AUDIO_URL = "/audio/bot-running/bot-running.webm";
export const TURNING_AUDIO_URL = "/audio/turning/turning-loop.wav";

export const FOOTSTEP_AUDIO_URLS = [
  "/audio/steps/step-01.wav",
  "/audio/steps/step-02.wav",
  "/audio/steps/step-03.wav",
  "/audio/steps/step-04.wav",
  "/audio/steps/step-05.wav",
  "/audio/steps/step-06.wav",
  "/audio/steps/step-07.wav",
  "/audio/steps/step-08.wav",
  "/audio/steps/step-09.wav",
  "/audio/steps/step-10.wav",
  "/audio/steps/step-11.wav",
  "/audio/steps/step-12.wav",
] as const;
